-- Migration: Analytics Schema Improvements
-- Created: 2026-02-01
-- Description:
--   1. Clean orphaned analytics data (referential integrity prep)
--   2. Add FK constraints with CASCADE DELETE on child -> analytics_sessions
--   3. Add new columns: is_bot (analytics_sessions), byte_size (session_recording_events)
--   4. Narrow x/y to SMALLINT on heatmap_clicks
--   5. Create analytics_daily_summary pre-aggregation table
--   6. Add composite indexes for common query patterns
--
-- IMPORTANT: Steps 1-5 run inside a transaction. Step 6 (CONCURRENTLY indexes)
--            must run outside the transaction block.
-- ============================================================================


-- ============================================================================
-- STEP 1: CLEAN ORPHANED DATA
-- ============================================================================
-- Before adding FK constraints we must remove any rows in child tables whose
-- session_id does not match an existing analytics_sessions.id. If these rows
-- remain, the ALTER TABLE ... ADD CONSTRAINT will fail.
-- ============================================================================

DELETE FROM "page_views"
WHERE "session_id" NOT IN (
    SELECT "id" FROM "analytics_sessions"
);

DELETE FROM "heatmap_clicks"
WHERE "session_id" NOT IN (
    SELECT "id" FROM "analytics_sessions"
);

DELETE FROM "session_recording_events"
WHERE "session_id" NOT IN (
    SELECT "id" FROM "analytics_sessions"
);


-- ============================================================================
-- STEP 2: ADD FOREIGN KEY CONSTRAINTS WITH CASCADE DELETE
-- ============================================================================
-- These enforce referential integrity: every child row must reference a valid
-- session. When a session is deleted, all its child rows are removed
-- automatically (CASCADE).
-- ============================================================================

-- PageView -> AnalyticsSession
ALTER TABLE "page_views"
    ADD CONSTRAINT "page_views_session_id_fkey"
    FOREIGN KEY ("session_id")
    REFERENCES "analytics_sessions"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- HeatmapClick -> AnalyticsSession
ALTER TABLE "heatmap_clicks"
    ADD CONSTRAINT "heatmap_clicks_session_id_fkey"
    FOREIGN KEY ("session_id")
    REFERENCES "analytics_sessions"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- SessionRecordingEvent -> AnalyticsSession
ALTER TABLE "session_recording_events"
    ADD CONSTRAINT "session_recording_events_session_id_fkey"
    FOREIGN KEY ("session_id")
    REFERENCES "analytics_sessions"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;


-- ============================================================================
-- STEP 3: ADD NEW COLUMNS
-- ============================================================================

-- 3a. analytics_sessions.is_bot  (Boolean, default false)
--     Flags sessions generated by crawlers/bots so dashboard queries can
--     exclude them. Default false means existing rows are treated as human.
ALTER TABLE "analytics_sessions"
    ADD COLUMN "is_bot" BOOLEAN NOT NULL DEFAULT false;

-- 3b. session_recording_events.byte_size  (nullable Int)
--     Stores the serialized payload size for each recording batch. Nullable
--     because historical rows were inserted before this column existed.
ALTER TABLE "session_recording_events"
    ADD COLUMN "byte_size" INTEGER;


-- ============================================================================
-- STEP 4: NARROW x/y TO SMALLINT ON heatmap_clicks
-- ============================================================================
-- These columns store click coordinates as percentage values (0-100 or
-- viewport-relative). SMALLINT (-32768 to 32767) is more than sufficient and
-- cuts storage per row from 8 bytes to 4 bytes for these two columns.
--
-- ALTER TYPE with USING casts the existing INTEGER data to SMALLINT. Any value
-- outside SMALLINT range would raise an error (none expected for percentages).
-- ============================================================================

ALTER TABLE "heatmap_clicks"
    ALTER COLUMN "x" SET DATA TYPE SMALLINT
    USING "x"::SMALLINT;

ALTER TABLE "heatmap_clicks"
    ALTER COLUMN "y" SET DATA TYPE SMALLINT
    USING "y"::SMALLINT;


-- ============================================================================
-- STEP 5: CREATE analytics_daily_summary TABLE
-- ============================================================================
-- Pre-aggregated daily metrics table. A scheduled job (or edge function)
-- computes these once per day so dashboard queries read from here instead of
-- scanning millions of raw rows.
--
-- Design decisions:
--   - UUID primary key (consistent with all other tables in this schema)
--   - summary_date is DATE with UNIQUE constraint (one row per day)
--   - JSONB columns for breakdowns allow flexible key-value aggregation
--     without schema changes when new dimensions are added
--   - Decimal(8,2) for avg_session_duration supports up to 999999.99 seconds
--   - All integer counters default to 0; JSONB defaults to empty object/array
-- ============================================================================

CREATE TABLE "analytics_daily_summary" (
    "id"                   UUID            NOT NULL DEFAULT gen_random_uuid(),
    "summary_date"         DATE            NOT NULL,
    "total_sessions"       INTEGER         NOT NULL DEFAULT 0,
    "unique_visitors"      INTEGER         NOT NULL DEFAULT 0,
    "total_page_views"     INTEGER         NOT NULL DEFAULT 0,
    "avg_session_duration" DECIMAL(8,2)    NOT NULL DEFAULT 0,
    "bounce_count"         INTEGER         NOT NULL DEFAULT 0,
    "top_pages"            JSONB           NOT NULL DEFAULT '[]'::jsonb,
    "device_breakdown"     JSONB           NOT NULL DEFAULT '{}'::jsonb,
    "country_breakdown"    JSONB           NOT NULL DEFAULT '{}'::jsonb,
    "browser_breakdown"    JSONB           NOT NULL DEFAULT '{}'::jsonb,
    "referrer_breakdown"   JSONB           NOT NULL DEFAULT '{}'::jsonb,
    "created_at"           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "analytics_daily_summary_pkey" PRIMARY KEY ("id")
);

-- One row per day -- enforced at the database level
CREATE UNIQUE INDEX "analytics_daily_summary_summary_date_key"
    ON "analytics_daily_summary"("summary_date");

-- Primary query pattern: ORDER BY summary_date DESC LIMIT N (dashboard chart)
CREATE INDEX "idx_ads_summary_date"
    ON "analytics_daily_summary"("summary_date" DESC);

-- Table-level documentation
COMMENT ON TABLE "analytics_daily_summary"
    IS 'Pre-aggregated daily analytics metrics for fast dashboard queries';
COMMENT ON COLUMN "analytics_daily_summary"."summary_date"
    IS 'Calendar date this row summarizes (UTC)';
COMMENT ON COLUMN "analytics_daily_summary"."top_pages"
    IS 'JSONB array of {path, views} objects, ordered by views desc';
COMMENT ON COLUMN "analytics_daily_summary"."device_breakdown"
    IS 'JSONB object: {"desktop": N, "mobile": N, "tablet": N}';
COMMENT ON COLUMN "analytics_daily_summary"."country_breakdown"
    IS 'JSONB object: {"SA": N, "AE": N, ...} keyed by ISO 3166-1 alpha-2';


-- ============================================================================
-- STEP 6: ADD COMPOSITE INDEXES
-- ============================================================================
-- These are created with CREATE INDEX CONCURRENTLY so they do not hold an
-- exclusive lock on the table during build. This is critical for production
-- deployments on tables that may already have significant data.
--
-- NOTE: CONCURRENTLY cannot run inside a transaction block. If this migration
-- is executed by Prisma (which wraps in a transaction), these statements will
-- automatically fall back to a standard CREATE INDEX. For manual production
-- deployment, run steps 1-5 first, then run step 6 separately outside a
-- transaction.
-- ============================================================================

-- 6a. page_views(session_id, created_at DESC)
--     Covers: "list page views for a session, most recent first"
--     Used by: session detail view, session replay timeline
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_pv_session_created"
    ON "page_views"("session_id", "created_at" DESC);

-- 6b. page_views(created_at, path)
--     Covers: "page views in a date range filtered/grouped by path"
--     Used by: top-pages report, path-level analytics
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_pv_created_path"
    ON "page_views"("created_at", "path");

-- 6c. heatmap_clicks(path, created_at)
--     Covers: "all clicks on a given page in a date range"
--     Used by: heatmap overlay rendering
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_hc_path_created"
    ON "heatmap_clicks"("path", "created_at");

-- 6d. analytics_sessions(visitor_id, started_at DESC)
--     Covers: "all sessions for a visitor, most recent first"
--     Used by: visitor profile / history view
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_as_visitor_started"
    ON "analytics_sessions"("visitor_id", "started_at" DESC);

-- 6e. analytics_sessions(started_at, country)
--     Covers: "sessions in a date range grouped/filtered by country"
--     Used by: geo analytics dashboard widget
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_as_started_country"
    ON "analytics_sessions"("started_at", "country");

-- 6f. analytics_sessions(started_at, device)
--     Covers: "sessions in a date range grouped/filtered by device type"
--     Used by: device breakdown dashboard widget
CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_as_started_device"
    ON "analytics_sessions"("started_at", "device");
